name: 'Deploy'

on:
  workflow_dispatch:
    inputs:
      environment_type:
        description: 'Environment type (prod, dev, test etc.)'
        required: true
      environment_id:
        description: 'An identifier used to distinguish environment with the same type'
        required: true
      version:
        description: 'Version to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Verify version'
        uses: mukunku/tag-exists-action@v1.0.0
        id: version
        with:
          tag: v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Fail'
        if: ${{ steps.version.outputs.exists != 'true' }}
        run: |
          echo ::error::The version ${{ github.event.inputs.version }} does not exist
          exit 1
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.version }}
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Deploy'
        env:
          RAPIDAPI_PROXY_SECRET: ${{ secrets.RAPIDAPI_PROXY_SECRET }}
          LINGUAROBOT_SECRET: ${{ secrets.LINGUAROBOT_SECRET }}
        run: |
          mvn -B clean deploy \
          -P\!dev,deployment \
          -Denvironment.type=${{ github.event.inputs.environment_type }} \
          -Denvironment.id=${{ github.event.inputs.environment_id  }} \
          -Drapidapi.proxy.secret=$RAPIDAPI_PROXY_SECRET \
          -Dlinguarobot.secret=$LINGUAROBOT_SECRET