name: 'Integration Test'

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'   

jobs:
  build:
    name: 'Build'
    strategy:
      matrix:
        java: [ '8', '11', '13', '14' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: 'Print Java Version'
        run: 'java -version'
      - name: 'Print GitHub Run Number'
        run: 'echo $GITHUB_RUN_NUMBER'
      - name: 'Print GitHub Context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
