name: 'Integration Test'

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'     
        required: false
        default: 'master'
  repository_dispatch:
    types: [integration-test-command]

jobs:
  integration-test:
    name: 'Integration Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Extract Repository Dispatch Input'
        if: ${{ github.event_name == 'repository_dispatch' }}
        id: repository-dispatch-input
        run: |
          echo ::set-output name=branch::${{ github.event.client_payload.pull_request.head.label }}
          echo ::set-output name=actor::${{ github.event.client_payload.github.payload.comment.user.login }}
          echo ::set-output name=actorUrl::${{ github.event.client_payload.github.payload.comment.user.html_url }}
      - name: 'Extract Workflow Dispatch Input'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: workflow-dispatch-input
        run: |
          echo ::set-output name=branch::${{ github.event.inputs.branch }}
          echo ::set-output name=actor::${{ github.event.sender.login }}
          echo ::set-output name=actorUrl::${{ github.event.sender.html_url }}
      - name: 'Extract Input'
        id: input
        run: |
          echo ::set-output name=branch::${{ steps.repository-dispatch-input.outputs.branch }}${{ steps.workflow-dispatch-input.outputs.branch }}
          echo ::set-output name=actor::${{ steps.repository-dispatch-input.outputs.actor }}${{ steps.workflow-dispatch-input.outputs.actor }}
          echo ::set-output name=actorUrl::${{ steps.repository-dispatch-input.outputs.actorUrl }}${{ steps.workflow-dispatch-input.outputs.actorUrl }}
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: 'Find Pull Request'
        id: find-pull-request
        uses: juliangruber/find-pull-request-action@v1.3.0
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          branch: ${{ steps.input.outputs.branch }}
      - name: 'Post Status Comment'
        if: ${{ steps.find-pull-request.outputs.number != '' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ steps.find-pull-request.outputs.number }}
          body: |
            The integration tests have been started.

            **User:**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[${{ steps.input.outputs.actor }}](${{ steps.input.outputs.actorUrl }})
            **Status:**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[${{ github.workflow }}#${{github.run_number}}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ steps.find-pull-request.outputs.head-sha }}
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Run integration tests'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mvn -B clean verify \
          -Daws.region=${{ secrets.AWS_REGION }} \
          -Daws.account=${{ secrets.AWS_ACCOUNT }} \
          -DskipUTs=true \
          -DskipITs=false