name: 'Publish'

on:
  release:
    types: [created]

jobs:
  publish_package:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: 'Set up Environment'
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
#      - name: 'Set up GPG secret key'
#        run: |
#          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: 'Publish to Maven Central Repository'
        env:
          MAVEN_USERNAME: RoKish
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B \
            -Prelease \
            -DskipUTs=true \
            -DskipITs=true \
            clean deploy