name: 'Publish'

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  publish_package:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - name: 'Dump Github Context'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: 'Extract Release Published Input'
        if: ${{ github.event_name == 'release' }}
        id: release-published-input
        run: |
          echo ::set-output name=version::${{ github.event.release.tag_name }}
      - name: 'Extract Workflow Dispatch Input'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        id: workflow-dispatch-input
        run: |
          echo ::set-output name=version::${{ github.event.inputs.version }}
      - name: 'Extract Input'
        id: input
        run: |
          echo ::set-output name=version::${{ steps.release-published-input.outputs.version }}${{ steps.workflow-dispatch-input.outputs.version }}
      - name: 'Checkout'
        with:
          ref: ${{ steps.input.outputs.version }}
        uses: actions/checkout@v2
      - name: 'Set up Environment'
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: 'Publish to Github Packages'
        env:
          MAVEN_USERNAME: RoKish
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: 'mvn -B -Prelease clean deploy'
